javascript:
  splash.js: javascripts/splash.js
  president.js: javascripts/president.js
  senate.js: javascripts/senate.js
  house.js: javascripts/house.js
  region.js: javascripts/region.js
  splash/desktop.js: javascripts/splash/desktop.js

scss:
  dashboard.css: stylesheets/dashboard.scss
  mobile-ad.css: stylesheets/mobile-ad.scss
  splash.css: stylesheets/splash.scss
  splash-desktop.css: stylesheets/splash-desktop.scss
  splash-bar.css: stylesheets/splash-bar.scss

digest:
  -
    pattern: javascripts/{stats,social}.js
    max_age: 8640000000
  -
    pattern: images/**/*.{png,jpg,gif,svg,ico}
    max_age: 8640000000
  -
    pattern: maps/**/*.{png,svg}
    max_age: 8640000000
  -
    pattern: fonts/**/*.woff
    max_age: 8640000000
