javascript:
  splash.js: javascripts/splash.js
  president.js: javascripts/president.js
  splash/desktop.js: javascripts/splash/desktop.js

scss:
  dashboard.css: stylesheets/dashboard.scss
  splash.css: stylesheets/splash.scss

digest:
  -
    pattern: javascripts/{stats,social}.js
    max_age: 8640000000
  -
    pattern: images/**/*.{png,jpg,gif,svg,ico}
    max_age: 8640000000
  -
    pattern: maps/**/*.{png,svg}
    max_age: 8640000000
