index:
  path: _root
  redirect: president

# GET /splash.js
#
# JavaScript file that assumes it's being loaded into the Huffington Post
# front page. It will search for certain DOM IDs and replace the contents
# of those elements.
splash.js:
  model: splash
  headers:
    Content-Type: application/javascript

splash/:locale:
  collection: translatedSplash
  template: splash/desktop

# GET /_test/splash/:format
#
# A fake Huffington Post front page, with holes where the splash should fit in.
#
# This page doesn't have all the clunk of an actual Huffington Post front page.
# It's meant to be enough to check that styles and layout all work nicely.
_test/splash/:format:
  template: _test/splash
  collection: splashFormats

_test/splash/i18n:
  template: _test/i18n-splash
  model: translatedSplash

president:
  model: president

senate:
  model: senate

house:
  model: house

president.json:
  model: presidentAsBuffer
  headers:
    Content-Type: application/json
    Cache-Control: public, max-age=5

house.json:
  model: houseAsBuffer
  headers:
    Content-Type: application/json
    Cache-Control: public, max-age=5
